apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fiapfase5
type: Opaque
stringData:
  SQL_SA_PASSWORD: "Fiap@123"

  JWT_SECRET_KEY: "1234567891123456789212345678931234667894"
  JWT_ISSUER: "SuaAppFiap"
  JWT_AUDIENCE: "FiapFase5"

  RABBITMQ_USER: "admin"
  RABBITMQ_PASS: "admin"