apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry
  namespace: fiapfase5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry
  template:
    metadata:
      labels:
        app: telemetry
    spec:
      containers:
        - name: telemetry
          image: fiap/telemetry:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver,1433;Database=DB_Fase5_Telemetry;User Id=sa;Password=Fiap@123;TrustServerCertificate=True"

            - name: Jwt__SecretKey
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET_KEY
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_ISSUER
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_AUDIENCE
            - name: Jwt__ExpiresInMinutes
              value: "2000"

            - name: RabbitMq__HostName
              value: "rabbitmq"
            - name: RabbitMq__Port
              value: "5672"
            - name: RabbitMq__UserName
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_USER
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_PASS
            - name: RabbitMq__QueueName
              value: "telemetry.leituras"
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry
  namespace: fiapfase5
spec:
  selector:
    app: telemetry
  ports:
    - port: 80
      targetPort: 8080