// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telemetry.Infrastructure.Data;

#nullable disable

namespace Telemetry.Infrastructure.Migrations
{
    [DbContext(typeof(DbContextTelemetry))]
    partial class DbContextTelemetryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("telemetria")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Telemetry.Domain.Entities.Alerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FechadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FimUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TalhaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Tipo")
                        .HasDatabaseName("IX_Alertas_Status_Tipo");

                    b.HasIndex("TalhaoId", "Status", "CriadoEmUtc")
                        .HasDatabaseName("IX_Alertas_Talhao_Status_CriadoEm");

                    b.ToTable("Alertas", "telemetria");
                });

            modelBuilder.Entity("Telemetry.Domain.Entities.LeituraSensor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataHoraLeituraUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precipitacao")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("RecebidoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TalhaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Temperatura")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("UmidadeSolo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("TalhaoId", "DataHoraLeituraUtc")
                        .HasDatabaseName("IX_Leituras_Talhao_DataHora");

                    b.ToTable("LeiturasSensores", "telemetria");
                });
#pragma warning restore 612, 618
        }
    }
}
