services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fiap_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fiap_sqlserver
    ports:
      - "14330:1433"  
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Fiap@123"
    volumes:
      - sqlserver_data:/var/opt/mssql

  grafana:
    image: grafana/grafana:latest
    container_name: fiap_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  sqlserver_data:
  grafana_data: